// <auto-generated />
namespace RentYourMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addGenre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addGenre));
        
        string IMigrationMetadata.Id
        {
            get { return "201812041632595_addGenre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
